### ISSUE TITLE
Vanishing talent points

### ISSUE THREAD

**Issue by Neverlight-Jyria** [Avalon-Classless/Bugtracker#14]
I did some excess testing regarding the vanishing talent point issues.

One way to make the talent points vanish is fully learn a talent. 
Fully unlearn it again.
Re-learn all of it & only unlearn 1 rank.
Press the Reset All talent button

This voids the talent points put in place

**Comment by OMGhixD-OG** [comment]
Thanks, we are aware of this and are working on it.

**Comment by Fiurs-Hearth** [comment]
Fixed, added warning text when trying to unlearn spells/talents when you do not have the required item.

**Comment by Fiurs-Hearth** [comment]
Added comments to the wrong issue.
Issue is not resolved yet.

**Comment by Fiurs-Hearth** [comment]
Fixed, now total amount of talent points are returned as expected
