### ISSUE TITLE
Gamebreaking issue: Unlearning talents lets u keep talents

### ISSUE THREAD

**Issue by Neverlight-Jyria** [Avalon-Classless/Bugtracker#15]
Main issue with the current classless experience is the way how talents are handled.
In its current state when u unlearn a talent u keep some ranks of the talents, both if u manually unlearn it or unlearn with the reset all button witch also voids talent point currency completely.

Additionally when u re-log the server thinks you do have all ranks of the talents so all talents get put back to their maxed state even tough the UI shows 0/5 ect.

Re-learning the talents back to max funny enough unlearns the talents partially instead again until u un-learn all ranks again to re-gain max rank on relog

**Comment by OMGhixD-OG** [comment]
Thanks, we are aware of this and are working on it.

**Comment by Cillez** [comment]
Fixed
