### ISSUE TITLE
Bag prices in vendors 500% increased

### ISSUE THREAD

**Issue by MichaelCrow** [Avalon-Classless/Bugtracker#2]
25 silver for something that takes minutes to just make yourself and drop the tailoring profession is probably a bad idea for a testing environment, if not the server entirely.

please drop 6 slot bags to 5 silver, 8 slot to 25silver and 10 and 12 to their regular wotlk amounts as well.

**Comment by OMGhixD-OG** [comment]
Noted thanks!

**Comment by Cillez** [comment]
Fixed
