### ISSUE TITLE
Racial Ability Trait Swapper

### ISSUE THREAD

**Issue by OMGhixD-OG** [Avalon-Classless/Bugtracker#20]
Quest/Spell/Item/Creature(ID) The ID is: Selector Au'Mar

The Current Behaviour is as following: Make a troll, attempt to aqcuire orc racials, do night elf. Now relog and you have Nelf and Troll racials. (This seems to be adjustable to almost every other race)

Expected Behaviour should be as following: Upon choosing a new racial set. It should remove all previous racials to replace with new ones.

Screenshot/Video (IMGUR/YOUTUBE): ![image](https://user-images.githubusercontent.com/3145839/187435766-201de40c-fcb8-43ef-8a33-fd351d085ec7.png)

Additional Information:

**Comment by OMGhixD-OG** [comment]
Update: Cillez has optimized the script. Unsure of the status on the bug reported. To be continued!

**Comment by Cillez** [comment]
Fixed on next restart
