### ISSUE TITLE
Class Quest/ Infinite Essences.

### ISSUE THREAD

**Issue by Madliv21** [Avalon-Classless/Bugtracker#22]
Quest: Any class quest

The Current Behaviour is as following: 

The player can unlearn a spell learned from the class quest (for free), gaining a point back. The player can log out/ log in to learn the spells once more, unlearning them for infinite points.

Expected Behaviour should be as following: 

Player should not get the spells back once relogging or spells learned by class trainer should not be unlearnable.

**Comment by OMGhixD-OG** [comment]
Should be fixed as of 13.09.22

Reference https://discordapp.com/channels/915382546286653500/925817071927971870/1019242905329745962

//Closing
