### ISSUE TITLE
Tooltip Erros/Missing information

### ISSUE THREAD

**Issue by Xenothang** [Avalon-Classless/Bugtracker#28]
Quest/Spell/Item/Creature(ID) The ID is: 
Like half of the spells in the fking spellbook XD
The Current Behaviour is as following: 
Taking any reduced cast time talent doesn't show the correct Tooltip time.
Same applies to any reduced Rage/energy/mana cost in talents for abilities.
Expected Behaviour should be as following: 
Should show proper stats on Cast time and rage/energy/mana
Screenshot/Video (IMGUR/YOUTUBE): 
Go ingame BRUH
Additional Information:
I think it worked on the last core

**Comment by OMGhixD-OG** [comment]
Noted Thanks!
