### ISSUE TITLE
Addon Lock will glitch onto additional addons

### ISSUE THREAD

**Issue by OMGhixD-OG** [Avalon-Classless/Bugtracker#29]
The Current Behaviour is as following: You can scroll down in the addon list and a visual bug will apply to the lower addon(s). The lock which is present on AIO addon

Expected Behaviour should be as following: Should not happen.

Screenshot/Video (IMGUR/YOUTUBE): ![Image](https://cdn.discordapp.com/attachments/1012791555364499526/1019209436616728606/unknown.png)

Additional Information:

**Comment by Fiurs-Hearth** [comment]
Fixed
