### ISSUE TITLE
Spell: Charge not usable while shapeshifted

### ISSUE THREAD

**Issue by Fiurs-Hearth** [Avalon-Classless/Bugtracker#32]
Quest/Spell/Item/Creature(ID) The ID is: 
ID: 100
Name: Charge

The Current Behaviour is as following: 
Tooltips states that it is usable while shapeshifted but it is not usable while shapeshifted

Expected Behaviour should be as following: 
To be usable while shapeshifted

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by OMGhixD-OG** [comment]
This works as intentional. Unsure if we applied a fix along the road. But i'm unable to replicate atleast.

//Marking as fixed
