### ISSUE TITLE
aurastate to proc riposte, counterattack, and victory rush not availible due to class

### ISSUE THREAD

**Issue by MichaelCrow** [Avalon-Classless/Bugtracker#4]
solution: go into unit.cpp around line 10095 or so and remove the class specifications for one of the defensive aurastates. Same deal for victory rush but its somewhere else in the source.

**Comment by OMGhixD-OG** [comment]
Riposte and Counterattack was fixed as of 27.08.22 - 7:00PM
Source: https://discord.com/channels/915382546286653500/925817071927971870/1013130870229581854

Will keep this open as Victory Rush remains bugged.

Thanks for your report!

**Comment by OMGhixD-OG** [comment]
Victory Rush should now be fixed. Awaiting deployment however.

//Closing for now. Reopen if issue is not fixed
