### ISSUE TITLE
Unable to do Class Quests

### ISSUE THREAD

**Issue by Neverlight-Jyria** [Avalon-Classless/Bugtracker#5]
Due to the "classless" class (druid?) you are unable to do other class quests. This would make it so Whirlwind Axe is unobtainable and a few other quests that would make your questing experience better.

**Comment by OMGhixD-OG** [comment]
Noted thanks!

**Comment by OMGhixD-OG** [comment]
@JyriaLycion can you do me a favor and list the quests in question?

**Comment by OMGhixD-OG** [comment]
All quests are now available to players.

*(Awaiting server restart for this to take effect)*

Thank you for reporting!

//Closed
