### ISSUE TITLE
Deputy Willem in Northshire Valley constantly in talking animation

### ISSUE THREAD

**Issue by mdjong1** [Avalon-Classless/Bugtracker#7]
Quest/Spell/Item/Creature(ID) The ID is: 
Deputy Willem in Northire Valley, not sure of the Creature ID

The Current Behaviour is as following: 
He is constantly in a talking animation

Expected Behaviour should be as following: 
He should also be chilling sometimes, talking non-stop is tiring

Screenshot/Video (IMGUR/YOUTUBE): 
![image](https://user-images.githubusercontent.com/4410453/186992700-824eca94-646a-4742-800f-b8837f6b6e22.png)

Additional Information:

**Comment by OMGhixD-OG** [comment]
Someone messing with .npc emote command for fun during alpha :)
