### ISSUE TITLE
Typo in Ability Essence

### ISSUE THREAD

**Issue by mdjong1** [Avalon-Classless/Bugtracker#8]
Quest/Spell/Item/Creature(ID) The ID is: 
`Ability Essence`

The Current Behaviour is as following: 
Small type in Ability Essence

Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE): 
Drop the s
![image](https://user-images.githubusercontent.com/4410453/187030016-add3c290-4342-4688-be47-4f77518b0823.png)

Additional Information:

**Comment by OMGhixD-OG** [comment]
Appreciate it, fixed now.

Requires restart and cache clear
