### ISSUE TITLE
Possible to unlearn summon but keep the summoned pet

### ISSUE THREAD

**Issue by mdjong1** [Avalon-Classless/Bugtracker#9]
Quest/Spell/Item/Creature(ID) The ID is: 
At least witnessed with an Imp, probably others as well

The Current Behaviour is as following: 
When you unlearn `summon Imp` you get to keep the imp

Expected Behaviour should be as following: 
When unlearning the summon spell the summoned minion/pet/whatever should be despawned

Screenshot/Video (IMGUR/YOUTUBE): 
![image](https://user-images.githubusercontent.com/4410453/187030096-48ed0fc7-6c5c-4178-922f-4d0193166d03.png)

Additional Information:

**Comment by OMGhixD-OG** [comment]
Noted thanks!

**Comment by Fiurs-Hearth** [comment]
**Added** status "Fixed and deployed" since it's not the best fix but its a temporary fix for now.
